id: I90736A00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:57:55+00:00'
last_modified: '2022-06-08T16:19:34.942403+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25587
  title: དྲེལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    3D74:
      image_group_id: I1KG25589
      title: ''
      total_pages: 224
      order: 1
      base_file: 3D74.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
